Add friends likes
ToxicCritic/filmorate pull request #2
Opened 2024-12-31 16:30 UTC by ToxicCritic

Доброго времени суток, Tomattman
Не получается настроить валидацию через аннотацию @Email, просто исключение не бросается, помогите пожалуйста. Проверить можно в тесте shouldThrowExceptionForInvalidEmail класса UserControllerUnitTest. 
Спасибо и с праздниками!

2025-01-01 14:15 UTC, tomattman requested changes
Привет, работа отличная, единственный коммент я добавил, стоит переделать это, а так же точно такая же проблема с друзьями

Теперь по поводу твоего вопроса
Вся суть проблемы в том, как спринг создает сервисы, если ты поставишь брэйкпоинт на какую ни будь строчку в контроллере, и остановишься на нем, то ты сможешь увидеть что в переменной сервиса записан не сам объект сервиса, а обёртка вокруг него.
Именно так работает спринг, каждый компонент по сути обернут  в обертку которая уже знает как обрабатывать все аннотации которые мы добавили в класс
В тесте же ты создаешь просто класс контроллера, через конструктор, и этот класс не умеет ничего из того что может делать его компонент. Для того чтобы тест заработал тебе надо запустить его с спринговом контексте, и чтобы он подтянулся в тест как компонент
погугли аннотацию  springboottest

2025-01-01 14:15 UTC, tomattman commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +    private final Map<Long, Set<Long>> likes = new HashMap<>();
если у тебя есть filmStorage то значит что у тебя есть слой хранилища, так почему данные хранятся на разных слоях, фильмы в хранилище а лайки в сервисе? 
стоит их перенести либо в хранилище фильмов, либо в хранилище пользователей, ну или можно сделать отдельное хранилище лайков

2025-01-02 09:40 UTC, tomattman approved these changes
Принято, хотя тесты не поправлены

2025-01-02 13:43 UTC, ToxicCritic commented
@tomattman Я почитал про аннотацию SpringBootTest, как я понял работать тест будет либо если указать параметр webEnvironment (Запустить сервер целиком) либо через Mock-объект MockMvc и аннотацию WebMvcTest. Думаю мы затронем по курсу это позже и я допишу, так довольно сложно было разобраться.

2025-01-02 13:43 UTC, merged